#!/usr/bin/env ruby
# ==============================================================================
# Purpose:
#     Initialize the PiB-related Beagle output subdirectories.
#
# ==============================================================================

require 'optparse'
require 'ostruct'
require 'pathname'
require 'fileutils'
require 'tmpdir'            # needed for Dir::tmpdir

# load ruby gems
require 'rubygems'
require 'json'
require 'pp'

# load external dependencies
require 'hclab_function_library'
require 'beagle_function_library'
require 'beagle_civet_function_library'
require 'beagle_logger_classes'

# start of main script
begin
   opt                     = OpenStruct.new{}   # store input options
   opt.verbose             = false
   opt.debug               = false
   opt.keyname             = ""
   opt.scanDate            = ""
   opt.civetScanDate       = ""
   opt.settingsFile        = ""

   # List of arguments.
   opts = OptionParser.new do |opts|
      opts.banner = "Usage: #{$0} [Options]"
      opts.separator ""
      opts.separator "Options:"

      opts.on('-v', '--[no-]verbose', 'Run verbosely') { |v| opt.verbose = v }

      opts.on('-d', '--debug', 'Print pedantic debugging messages') { |d| opt.debug = d }
   
      opts.on('--keyname subject_keyname', "Anonymizing keyname for this subject") do |keyname|
         opt.keyname = keyname
         puts "** keyname: " + opt.keyname if opt.verbose
      end

      opts.on('--scanDate pib_scan_date', "Usually a scan date of format YYYYMMDD") do |scanDate|
         opt.scanDate = scanDate
         puts "** PiB scan date: " + opt.scanDate if opt.verbose
      end

      opts.on('--civetScanDate civet_scan_date', "Usually a scan date of format YYYYMMDD") do |civetScanDate|
         opt.civetScanDate = civetScanDate
         puts "** Civet scan date: " + opt.civetScanDate if opt.verbose
      end

      opts.on('--settingsFile aggregated_settings_file', "Fullpath to the aggregated settings file ") do |settingsFile|
         opt.settingsFile = settingsFile.to_s
         puts "** Fullpath to the aggregated settings file: " + opt.settingsFile if opt.verbose
      end

      opts.on_tail("-h", "--help", "Show this very helpful help message") do
         puts opts
         exit
      end

   end  # OptionParser

   # run parse!() method in the OptionParser object, passing ARGV
   # NB: the "!" in parse!() removes the switches from ARGV
   puts "Before OptionParser start ..." if opt.debug
   opts.parse!(ARGV)



   # = = = = = = = =   M A I N   P R O C E S S I N G   S T A R T S   H E R E   = = = = = = =
   #

   # check for aggregated settings file, then read if all looks OK
   if ( opt.settingsFile.empty? ) then
      puts "\n*** Error: Missing option(s) -- Loris aggregated settings file"
      puts opts
      exit
   end
   #
   if ( !File.exists?(opt.settingsFile) || !File.file?(opt.settingsFile) ) then
      puts sprintf("\n!!! Error: The specified Loris aggregated settings [%s] does not exist or is unreadable.", opt.settingsFile)
      exit
   end
   #
   settings = load_beagle_aggregated_settings(opt.settingsFile, verbose=false, debug=false)


   # init associated variables
   LORIS_ROOT_DIR = settings['LORIS_ROOT_DIR']
   CIVET_VERSION = settings['CIVET_VERSION']


   # set some useful values
   #
   # are we going to use scan date to access the Civet output files/directories?
   keyname_dir_fullPath = File.join(settings['LORIS_ROOT_DIR'], opt.keyname)
   pibScan_dir = 'PiB-' + opt.scanDate

   # check Civet ID directory ... just make sure it's there
   civetId_dir_fullPath = civet_getScanDirectoryName(civet_keyname:opt.keyname, civet_scanid:opt.civetScanDate, settings:settings, opt:opt, fullpath:true, checkExistence:true)
   
   # load subject's master logfile; write a start message
   progname = 'beagle_pib_initialization'
   logger = BeagleLogger.new(opt.keyname, settings, eraseLog=false)
   logger.log_start_message(progname, opt.keyname, 'PiB', opt.scanDate)
   logger.log_message(progname, opt.keyname, 'PiB', opt.scanDate, 'civet_version', CIVET_VERSION)


   # new create PiB-related subdirs within this directory
   #
   # check PiB ID directory; then create PiB subdirectories
   pibScan_dir_fullPath = File.join(keyname_dir_fullPath, pibScan_dir)
   if ( !File.exists?(pibScan_dir_fullPath) ) then
      #puts pibScan_dir_fullPath
      Dir.mkdir(pibScan_dir_fullPath)
   end
   # write ID of associated anatomical scan into the directory
   civetScanDirectoryName = civet_getScanDirectoryName(civet_keyname:opt.keyname, civet_scanid:opt.civetScanDate, settings:settings, opt:opt)
   File.open(File.join(pibScan_dir_fullPath,'civet_scan_id.txt'), 'w') {|f| f.write("#{civetScanDirectoryName}\n");f.close}

   # create subdirs
   filename = File.join(pibScan_dir_fullPath, "native")
   if !File.exists?( filename ) then FileUtils.mkdir( filename ) end
   #
   filename = File.join(pibScan_dir_fullPath, "tal")
   if !File.exists?( filename ) then FileUtils.mkdir( filename ) end
   #
   filename = File.join(pibScan_dir_fullPath, "masks")
   if !File.exists?( filename ) then FileUtils.mkdir( filename ) end
   #
   filename = File.join(pibScan_dir_fullPath, "transforms")
   if !File.exists?( filename ) then FileUtils.mkdir( filename ) end
   #
   filename = File.join(pibScan_dir_fullPath, "ratios")
   if !File.exists?( filename ) then FileUtils.mkdir( filename ) end
   #
   filename = File.join(pibScan_dir_fullPath, "verify")
   if !File.exists?( filename ) then FileUtils.mkdir( filename ) end
   #
   filename = File.join(pibScan_dir_fullPath, "logs")
   if !File.exists?( filename ) then FileUtils.mkdir( filename ) end
   #
   filename = File.join(pibScan_dir_fullPath, "images")
   if !File.exists?( filename ) then FileUtils.mkdir( filename ) end
   #
   filename = File.join(pibScan_dir_fullPath, "tmp")
   if !File.exists?( filename ) then FileUtils.mkdir( filename ) end

   # log a 'done' message to the subject's master logfile, and then write out logfile
   logger.log_stop_message(progname, opt.keyname, 'PiB', opt.scanDate)
   logger.save_to_file()


rescue RuntimeError => e
   STDERR.puts e
   exit 1
end  #main()

