#!/usr/bin/env ruby
# ==============================================================================
# Purpose:
#     Generate verification images, following FDG preprocessing.
#
#     The primary purpose of the verification is to ensure that selected
#     critical structures were withing the field of view of the 
#     scanner.
#
#     For example, since the cerebellar gray is often used as a 
#     reference tissue, we need to know whether any of the cerebellum
#     was not scanned. Appropriate warnings are then issued.
#
# ==============================================================================

require 'optparse'
require 'ostruct'
require 'pathname'
require 'fileutils'
require 'tmpdir'            # needed for Dir::tmpdir

# load ruby gems
require 'rubygems'
require 'json'
require 'pp'

# load external dependencies
require 'hclab_function_library'
require 'beagle_function_library'
require 'beagle_civet_function_library'
require 'beagle_logger_classes'

# start of main script
begin
   opt                     = OpenStruct.new{}  # store input options
   opt.verbose             = false
   opt.debug               = false
   opt.fake                = false
   opt.keyname             = ""
   opt.scanDate              = ""
   opt.civetScanDate       = ""
   opt.settingsFile        = ""

   # List of arguments.
   opts = OptionParser.new do |opts|
      opts.banner = "Usage: #{$0} [Options]"
      opts.separator ""
      opts.separator "Options:"

      opts.on('-v', '--[no-]verbose', 'Run verbosely') { |v| opt.verbose = v }

      opts.on('-d', '--debug', 'Print pedantic debugging messages') { |d| opt.debug = d }

      opts.on('-f', '--fake', 'Do not actually execute the commands') { |f| opt.fake = f }

      opts.on('--keyname subject_keyname', "Anonymizing keyname for this subject") do |keyname|
         opt.keyname = keyname
         puts "** keyname: " + opt.keyname if opt.verbose
      end
      
      opts.on('--scanDate fdg_scan_date', "Usually a scan date of format YYYYMMDD") do |scanDate|
         opt.scanDate = scanDate
         puts "** scan Id: " + opt.scanDate if opt.verbose
      end
      
      opts.on('--civetScanDate civet_scan_date', "Usually a scan date of format YYYYMMDD") do |civetScanDate|
         opt.civetScanDate = civetScanDate
         puts "** Civet scan date: " + opt.civetScanDate if opt.verbose
      end

      opts.on('--settingsFile aggregated_settings_file', "Fullpath to the aggregated settings file ") do |settingsFile|
         opt.settingsFile = settingsFile.to_s
         puts "** Fullpath to the aggregated settings file: " + opt.settingsFile if opt.verbose
      end
 
      opts.on_tail("-h", "--help", "Show this very helpful help message") do
         puts opts
         exit
      end

   end  # OptionParser

   # run parse!() method in the OptionParser object, passing ARGV
   # NB: the "!" in parse!() removes the switches from ARGV
   puts "Before OptionParser start ..." if opt.debug
   opts.parse!(ARGV)



   # = = = = = = = =   M A I N   P R O C E S S I N G   S T A R T S   H E R E   = = = = = = =
   #

   # check for aggregated settings file, then read if all looks OK
   if ( opt.settingsFile.empty? ) then
      puts "\n*** Error: Missing option(s) -- Loris aggregated settings file"
      puts opts
      exit
   end
   #
   if ( !File.exists?(opt.settingsFile) || !File.file?(opt.settingsFile) ) then
      puts sprintf("\n!!! Error: The specified Loris aggregated settings [%s] does not exist or is unreadable.", opt.settingsFile)
      exit
   end
   #
   settings = load_beagle_aggregated_settings(opt.settingsFile, verbose=false, debug=false)

   # init associated variables
   LORIS_ROOT_DIR = settings['LORIS_ROOT_DIR']
   CIVET_VERSION = settings['CIVET_VERSION']
   FDG_CEREB_THOLD_PCT = settings['FDG_CEREB_THOLD_PCT'].to_f
   MASKS_CEREBELLUM_GM_FILENAME = settings['MASKS_CEREBELLUM_GM_FILENAME']


   # set some useful values
   keyname_dir_fullPath = File.join(settings['LORIS_ROOT_DIR'], opt.keyname)
   fdg_dir = 'FDG-' + opt.scanDate
   fdg_dir_fullPath = File.join(keyname_dir_fullPath, fdg_dir)
   fdgTmp_dir_fullPath = File.join(fdg_dir_fullPath, 'tmp')
   fdgLogs_dir_fullPath = File.join(fdg_dir_fullPath, 'logs')
   fdgNative_dir_fullPath = File.join(fdg_dir_fullPath, 'native')
   fdgTal_dir_fullPath = File.join(fdg_dir_fullPath, 'tal')
   fdgTransforms_dir_fullPath = File.join(fdg_dir_fullPath, 'transforms')
   fdgMasks_dir_fullPath = File.join(fdg_dir_fullPath, 'masks')
   fdgImages_dir_fullPath = File.join(fdg_dir_fullPath, 'images')
   #
   masks_dir = 'masks-' + opt.civetScanDate
   masks_dir_fullPath = File.join(keyname_dir_fullPath, masks_dir)
   CEREB_GM_MASK_VOLUME_FULLPATH = File.join(masks_dir_fullPath, MASKS_CEREBELLUM_GM_FILENAME)




   # * * * * *   Start of input argument validation   * * * * *

   # make sure that the input args were specified and are valid
   #
   # subject keyname been specified?
   if ( opt.keyname.empty? ) then
      puts "\n*** Error: A subject keyname must be specified"
      puts opts
      exit
   end

   # Civet scan date entered?
   if (opt.civetScanDate.empty? ) then
      puts "\n*** Error: Civet scan date is missing"
      puts opts
      exit
   end

   # check if the temporary working directory exists; if not, create it
   # Note: if often clear out the tmp dir at end of processing by 
   #       deleting it -- that's why we need to re-create it
   if !File.exists?(fdgTmp_dir_fullPath) then Dir.mkdir(fdgTmp_dir_fullPath) end
   #
   # * * * * *  END of input argument validation   * * * * * * * *
   # * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * 



   # load subject's master logfile; write a start message
   progname = 'beagle_fdg_preprocess_verification'
   logger = BeagleLogger.new(opt.keyname, settings, eraseLog=false)
   logger.log_start_message(progname, opt.keyname, 'FDG', opt.scanDate)
   logger.log_message(progname, opt.keyname, 'FDG', opt.scanDate, 'civet_version', CIVET_VERSION)

   # now that we've verified that we have a /logs subdir,
   # ... set processing status to "running"
   set_job_status(fdgLogs_dir_fullPath, "beagle_fdg_preprocess_verification_JobStatus", "running")



   # Firstly:
   # ... we want to ENSURE that our cerebellar gray matter was within the scanner field of view
   #
   # apply the gray matter mask against the FDG dynamic volume (in tal space)
   fdgVolname = opt.keyname + "_talAligned.mnc"
   fdgVolname_fullPath = File.join(fdgTal_dir_fullPath, fdgVolname)
   #
   masked_fdgVolname = opt.keyname + "_masked_fdgVol.mnc"
   masked_fdgVolname_fullPath = File.join(fdgTmp_dir_fullPath, masked_fdgVolname)
   #
   puts "\n** Apply cerebellar mask against FDG dynamic volume ..."   if opt.verbose
   cmd = "mincmath -clobber -verbose -mult  "
   cmd << "#{CEREB_GM_MASK_VOLUME_FULLPATH}   "
   cmd << "#{fdgVolname_fullPath}  "
   cmd << "#{masked_fdgVolname_fullPath}    "
   do_cmd(cmd, opt.verbose, opt.fake)

   # segment the masked FDG dynamic volume in order to find whether we have
   # any masked voxels without any significant intensity values
   binarized_masked_fdgVolname = opt.keyname + "_binarized_masked_fdgVol.mnc"
   binarized_masked_fdgVolname_fullPath = File.join(fdgMasks_dir_fullPath, binarized_masked_fdgVolname)
   puts "\n** Segment the masked FDG dynamic volume ..."   if opt.verbose
   #
   cmd = "mincmath -clobber -verbose -const2 -1 1 -nsegment  "
   cmd << "#{masked_fdgVolname_fullPath}   "
   cmd << "#{binarized_masked_fdgVolname_fullPath}  "
   do_cmd(cmd, opt.verbose, opt.fake)

   # get the total number of voxels comprising the cerebellar GM mask
   cmd = "mincstats #{CEREB_GM_MASK_VOLUME_FULLPATH}"
   puts "\n** Executing command: #{cmd} " if opt.verbose
   cmdResult = `#{cmd}`
   # get the sum of all mask voxels
   # ... split by EOL
   cmdResult = cmdResult.split
   # ... find the "Sum:" label, as the next index will be the Sum itself
   sumIndex = cmdResult.rindex("Sum:")
   gmMaskCount = cmdResult[sumIndex +1].to_i
   puts "\n** I see #{gmMaskCount} cerebellar voxels in the gray matter mask" 
   logger.log_message(progname, opt.keyname, 'FDG', opt.scanDate, 'nVox_in_cerebGMmask', gmMaskCount)
  
   # get the total number of voxels comprising the binarized masked dynamic volume
   cmd = "mincstats #{binarized_masked_fdgVolname_fullPath}"
   puts "\n** Executing command: #{cmd} " if opt.verbose
   cmdResult = `#{cmd}`
   # get the sum of all mask voxels
   # ... split by EOL
   cmdResult = cmdResult.split
   # ... find the "Sum:" label, as the next index will be the Sum itself
   sumIndex = cmdResult.rindex("Sum:")
   dynamicCount = cmdResult[sumIndex +1].to_i
   puts "\n** I see #{dynamicCount} non-zero intensity cerebellar voxels in the masked dynamic volume" 
   logger.log_message(progname, opt.keyname, 'FDG', opt.scanDate, 'nVox_in_adjustedCerebGMmask', dynamicCount)

   # if the voxel counts are not the same, then we have a problem
   # ... set error status and terminate
   #
   # OK, I've just played around a bit and noticed that the inferior-most cerebellar lobes are
   # often missing.  So I have a new solution: Let's permit a loss of up to 10 percent of the 
   # cerebellar voxels -- but let's make sure that we use the binarized DYNAMIC mask when
   # computing the cerebellar average. OK?
   #
   # ... error if too different
   pctInScanner = (dynamicCount.to_f / gmMaskCount.to_f) * 100.0
   logger.log_message(progname, opt.keyname, 'FDG', opt.scanDate, 'percent_included_voxels', pctInScanner)
   if ( pctInScanner < FDG_CEREB_THOLD_PCT ) then
      set_job_status(fdgLogs_dir_fullPath, "beagle_fdg_preprocess_verification_Warning", "error")
      puts sprintf("\n!!!Cerebellar gray matter not entirely in scanner field of view. I can only see %3.2f percent.", pctInScanner)
      puts("\n!!!This should be fixed.")
      #abort("\n!!!Die\n\n")
      #
   elsif ( pctInScanner < 100.0 and pctInScanner >= FDG_CEREB_THOLD_PCT ) then
      # ... warning if somewhat different ( > 75 percent)
      puts sprintf("\n???Cerebellar gray matter not entirely in scanner field of view. I can only see %3.2f percent.", pctInScanner)
      set_job_status(fdgLogs_dir_fullPath, "beagle_fdg_preprocess_verification_Warning", "warning")
   end
   
   
   # Next, create verification images:
   # ... first intensity normalize the stereotactic mean image
   # ... so that we can use meaningful threshold values
   #
   puts "\n** Image intensity normalization of verification image ..."   if opt.verbose
   cmd = "inormalize -clobber -verbose   "
   cmd << "-const2 0.0 95.0  -range 5.0  "
   cmd << "#{fdgTal_dir_fullPath}/#{opt.keyname}_talAligned.mnc   "
   cmd << "#{fdgTmp_dir_fullPath}/#{opt.keyname}_talAligned_normalized.mnc    "
   do_cmd(cmd, opt.verbose, opt.fake)


   # generate the images
   visualization_dir = File.join(keyname_dir_fullPath, 'visualization')
   anatomical_underlay_volume = civet_getFilenameStxT1(civet_keyname:opt.keyname, civet_scanid:opt.civetScanDate, settings:settings, opt:opt, fullpath:false)
   #
   puts "\n** Create verification image ..."   if opt.verbose
   cmd = "mincthumbs -v   "
   cmd << "-tthresh   20  "
   cmd << "-opacity .6  "
   cmd << "-tceiling  100  "
   cmd << "-contrast 1 "
   cmd << "-pos  "
   cmd << "-out #{fdgImages_dir_fullPath}/#{opt.keyname}_talAligned.pdf    "
   cmd << "#{fdgTmp_dir_fullPath}/#{opt.keyname}_talAligned_normalized.mnc   "
   cmd << "#{visualization_dir}/#{anatomical_underlay_volume} "
   do_cmd(cmd, opt.verbose, opt.fake)
   #
   # clean up the tmp dir
   #FileUtils.rm Dir.glob("#{fdgTmp_dir_fullPath}/*")


   # set processing status to "finished"
   set_job_status(fdgLogs_dir_fullPath, "beagle_fdg_preprocess_verification_JobStatus", "finished")

   # log a 'done' message to the subject's master logfile, and then write out logfile
   logger.log_stop_message(progname, opt.keyname, 'FDG', opt.scanDate)
   logger.save_to_file()

rescue RuntimeError => e
   STDERR.puts e
   exit 1
end  # main()

